import { Header } from "@/components/Header";
import { ModalProvider } from "@/context";
import { Modal } from "@/components/Modal";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ModalProvider>
          <Header />
          {children}
          <Modal />
          <div id="modal-root" />
        </ModalProvider>
      </body>
    </html>
  );
}
